# permissions for end users to view ckinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ckinstance-viewer-role
rules:
- apiGroups:
  - ckop.yt9999.io
  resources:
  - ckinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ckop.yt9999.io
  resources:
  - ckinstances/status
  verbs:
  - get
