apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ccc
  namespace: test
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

