apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccc
  namespace: test
  labels:
    app: ccc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccc
  template:
    metadata:
      labels:
        app: ccc
    spec:
      containers:
      - name: ccc
        image: clickhouse/clickhouse-server:21.8.15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: ccc
          mountPath: /etc/clickhouse-server/config.d/
      volumes:
      - name: ccc
        persistentVolumeClaim:
          claimName: ccc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ccc
  namespace: test
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

